// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ndyjtlgvmdtonrhptvsr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5keWp0bGd2bWR0b25yaHB0dnNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3NzI2NzQsImV4cCI6MjA2NDM0ODY3NH0.ynrGIUQJ3sN-s32fKbINzVyXpcd_AzJbBwvn3hB8V_Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);